# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            BlackDoc
tagline:          Black Theme for Jekyll
description:      "A two-column black theme with a scrolling sidebar. Ideal for sites requiring a master-detail layout, e.g. documentation, cheatsheets, lyrics, notes..."
url:              https://github.com/karloespiritu/blackdoc
baseurl:          /

author:
  name:           Karlo Espiritu
  url:            https://twitter.com/karloespiritu

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.0
sidebar_home_link:  true

github:
  repo:             https://github.com/karloespiritu/blackdoc
